### ISSUE TITLE
Develop the plugin engine

### ISSUE THREAD

**Issue by matheuswhite** [matheuswhite/scope-rs#108]
# TODOs
- [x] Fix error on hex string decoding and encoding
- [x] Add source to log messages: `[source:id] message`
- [x] Add a error message to plugin user command not found
- [x] Remove rust mentions from the plugin's error messages
- [x] Add helper functions on `scope.lua` to handle invalid inputs
- [x] Fix `on_serial_connect` and `on_serial_disconnect` baudrate
- [x] Test regex api of `scope.lua`
- [x] Add prefix `serial` to !connect and !disconnect commands
